### ISSUE TITLE
There is nothing in this project

### ISSUE THREAD

**Issue by Software-Cat** [Two-Guys-That-Can-Program/The-New-Digital-Age#1]
**What** do _we_ `do`?

**Comment by AnonymousPokeguy21** [comment]
### Samson's 5 Step Plan for Making a Website
1. Figure out what the website will be about (we've done that: oversimplifying information about new/emerging technologies)
2. Find some good technologies that are somewhat hard to understand (relative to our target audience: Ms Stacey or just teachers in general)
3. Type the information up but simpler (less jargon, explain important but obscure words)
4. Translate the script onto the website
5. Make a good StyleSheet and add anything else that makes the website look good

**Comment by Software-Cat** [comment]
We have good stuff!
This task is done!
